$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
        loop:true,
        nav:false,
        autoplay:true,
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
                nav:false
            },
            600:{
                items:1,
                nav:false,
                loop:true
            },
            1000:{
                items:2,
                nav:false,
                loop:true
            },
            1200:{
                items:4,
                nav:false,
                loop:true
            },
            2000:{
                items:4,
                nav:false,
                loop:true
            }
        }
    })
  });
  var mixer = mixitup('.grid-protfolio-container');